include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Your existing overrides
    avoid_print: false
    prefer_single_quotes: true

    # -------------------------
    # 🚨 Error-Prone / Safety
    # -------------------------
    always_use_package_imports: false
    avoid_empty_else: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_relative_imports: true
    throw_in_finally: true
    unnecessary_await_in_return: true

    # -------------------------
    # 🧹 Code Quality & Cleanliness
    # -------------------------
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_renaming_method_parameters: true
    avoid_setters_without_getters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    directives_ordering: true
    eol_at_end_of_file: true
    leading_newlines_in_multiline_strings: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_if_null_operators: true
    prefer_typing_uninitialized_variables: true
    require_trailing_commas: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_pub_dependencies: true
    type_annotate_public_apis: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_to_list_in_spreads: true

    # -------------------------
    # ⚡ Performance
    # -------------------------
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    prefer_const_declarations: true
    use_decorated_box: true
    use_colored_box: true
    use_enums: true

    # -------------------------
    # 🎯 Pedantic / Formatting
    # -------------------------
    always_declare_return_types: true
    annotate_overrides: true
    curly_braces_in_flow_control_structures: true
    omit_local_variable_types: false
    use_super_parameters: true
    sized_box_for_whitespace: true
    prefer_interpolation_to_compose_strings: true
    secure_pubspec_urls: true

    use_build_context_synchronously: false


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
