// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNIprSZrB7L9AzRuG6Yankn1MrSjL8t8U',
    appId: '1:298502075473:web:670aea690047a725d9b470',
    messagingSenderId: '298502075473',
    projectId: 'smart-task-manager-93463',
    authDomain: 'smart-task-manager-93463.firebaseapp.com',
    storageBucket: 'smart-task-manager-93463.firebasestorage.app',
    measurementId: 'G-J2KHQ6MNF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZQNIKGhmWLCz7O5r1k8HPYOPrQjcZKHE',
    appId: '1:298502075473:android:1b07063ade2df540d9b470',
    messagingSenderId: '298502075473',
    projectId: 'smart-task-manager-93463',
    storageBucket: 'smart-task-manager-93463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAedz_oCfrL14fqxgXxuqoNJKPe8yKGOvM',
    appId: '1:298502075473:ios:38e78e27172a550ad9b470',
    messagingSenderId: '298502075473',
    projectId: 'smart-task-manager-93463',
    storageBucket: 'smart-task-manager-93463.firebasestorage.app',
    iosBundleId: 'com.cyrilc.smartTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAedz_oCfrL14fqxgXxuqoNJKPe8yKGOvM',
    appId: '1:298502075473:ios:38e78e27172a550ad9b470',
    messagingSenderId: '298502075473',
    projectId: 'smart-task-manager-93463',
    storageBucket: 'smart-task-manager-93463.firebasestorage.app',
    iosBundleId: 'com.cyrilc.smartTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNIprSZrB7L9AzRuG6Yankn1MrSjL8t8U',
    appId: '1:298502075473:web:6e1bd3acd2d439bdd9b470',
    messagingSenderId: '298502075473',
    projectId: 'smart-task-manager-93463',
    authDomain: 'smart-task-manager-93463.firebaseapp.com',
    storageBucket: 'smart-task-manager-93463.firebasestorage.app',
    measurementId: 'G-KD5ZWBYZYL',
  );

}